version: "3.0"

services:
  insights5-blog:
    image: jekyll/jekyll:3.8
    container_name: insights5-blog
    volumes:
      - .:/srv/jekyll
    ports:
      - 8080:4000
    entrypoint: jekyll serve --verbose #-H localhost
